/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SetupAdminRouteImport } from './routes/setup-admin'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsDesktopRouteImport } from './routes/settings.desktop'
import { Route as AnalysisIdRouteImport } from './routes/analysis.$id'
import { Route as ApiInternal_cronSecretOnceRouteImport } from './routes/api/internal/__cron-secret-once'
import { Route as ApiPublicScriptsFileRouteImport } from './routes/api/public/scripts/$file'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsPlisioWebhookRouteImport } from './routes/api/public/payments/plisio-webhook'
import { Route as ApiPublicDesktopWhoamiRouteImport } from './routes/api/public/desktop/whoami'
import { Route as ApiPublicDesktopSubmitAnalysisRouteImport } from './routes/api/public/desktop/submit-analysis'
import { Route as ApiPublicDesktopPairRouteImport } from './routes/api/public/desktop/pair'
import { Route as ApiPublicCronPurgeInactiveRouteImport } from './routes/api/public/cron/purge-inactive'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAdminRoute = SetupAdminRouteImport.update({
  id: '/setup-admin',
  path: '/setup-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDesktopRoute = SettingsDesktopRouteImport.update({
  id: '/settings/desktop',
  path: '/settings/desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIdRoute = AnalysisIdRouteImport.update({
  id: '/analysis/$id',
  path: '/analysis/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternal_cronSecretOnceRoute =
  ApiInternal_cronSecretOnceRouteImport.update({
    id: '/api/internal/__cron-secret-once',
    path: '/api/internal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicScriptsFileRoute = ApiPublicScriptsFileRouteImport.update({
  id: '/api/public/scripts/$file',
  path: '/api/public/scripts/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsPlisioWebhookRoute =
  ApiPublicPaymentsPlisioWebhookRouteImport.update({
    id: '/api/public/payments/plisio-webhook',
    path: '/api/public/payments/plisio-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDesktopWhoamiRoute = ApiPublicDesktopWhoamiRouteImport.update({
  id: '/api/public/desktop/whoami',
  path: '/api/public/desktop/whoami',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDesktopSubmitAnalysisRoute =
  ApiPublicDesktopSubmitAnalysisRouteImport.update({
    id: '/api/public/desktop/submit-analysis',
    path: '/api/public/desktop/submit-analysis',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDesktopPairRoute = ApiPublicDesktopPairRouteImport.update({
  id: '/api/public/desktop/pair',
  path: '/api/public/desktop/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronPurgeInactiveRoute =
  ApiPublicCronPurgeInactiveRouteImport.update({
    id: '/api/public/cron/purge-inactive',
    path: '/api/public/cron/purge-inactive',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/setup-admin': typeof SetupAdminRoute
  '/upload': typeof UploadRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/settings/desktop': typeof SettingsDesktopRoute
  '/api/internal': typeof ApiInternal_cronSecretOnceRoute
  '/api/public/cron/purge-inactive': typeof ApiPublicCronPurgeInactiveRoute
  '/api/public/desktop/pair': typeof ApiPublicDesktopPairRoute
  '/api/public/desktop/submit-analysis': typeof ApiPublicDesktopSubmitAnalysisRoute
  '/api/public/desktop/whoami': typeof ApiPublicDesktopWhoamiRoute
  '/api/public/payments/plisio-webhook': typeof ApiPublicPaymentsPlisioWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/scripts/$file': typeof ApiPublicScriptsFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/setup-admin': typeof SetupAdminRoute
  '/upload': typeof UploadRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/settings/desktop': typeof SettingsDesktopRoute
  '/api/internal': typeof ApiInternal_cronSecretOnceRoute
  '/api/public/cron/purge-inactive': typeof ApiPublicCronPurgeInactiveRoute
  '/api/public/desktop/pair': typeof ApiPublicDesktopPairRoute
  '/api/public/desktop/submit-analysis': typeof ApiPublicDesktopSubmitAnalysisRoute
  '/api/public/desktop/whoami': typeof ApiPublicDesktopWhoamiRoute
  '/api/public/payments/plisio-webhook': typeof ApiPublicPaymentsPlisioWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/scripts/$file': typeof ApiPublicScriptsFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reports': typeof ReportsRoute
  '/setup-admin': typeof SetupAdminRoute
  '/upload': typeof UploadRoute
  '/analysis/$id': typeof AnalysisIdRoute
  '/settings/desktop': typeof SettingsDesktopRoute
  '/api/internal/__cron-secret-once': typeof ApiInternal_cronSecretOnceRoute
  '/api/public/cron/purge-inactive': typeof ApiPublicCronPurgeInactiveRoute
  '/api/public/desktop/pair': typeof ApiPublicDesktopPairRoute
  '/api/public/desktop/submit-analysis': typeof ApiPublicDesktopSubmitAnalysisRoute
  '/api/public/desktop/whoami': typeof ApiPublicDesktopWhoamiRoute
  '/api/public/payments/plisio-webhook': typeof ApiPublicPaymentsPlisioWebhookRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/scripts/$file': typeof ApiPublicScriptsFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/legal'
    | '/login'
    | '/pricing'
    | '/reports'
    | '/setup-admin'
    | '/upload'
    | '/analysis/$id'
    | '/settings/desktop'
    | '/api/internal'
    | '/api/public/cron/purge-inactive'
    | '/api/public/desktop/pair'
    | '/api/public/desktop/submit-analysis'
    | '/api/public/desktop/whoami'
    | '/api/public/payments/plisio-webhook'
    | '/api/public/payments/webhook'
    | '/api/public/scripts/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/legal'
    | '/login'
    | '/pricing'
    | '/reports'
    | '/setup-admin'
    | '/upload'
    | '/analysis/$id'
    | '/settings/desktop'
    | '/api/internal'
    | '/api/public/cron/purge-inactive'
    | '/api/public/desktop/pair'
    | '/api/public/desktop/submit-analysis'
    | '/api/public/desktop/whoami'
    | '/api/public/payments/plisio-webhook'
    | '/api/public/payments/webhook'
    | '/api/public/scripts/$file'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/history'
    | '/legal'
    | '/login'
    | '/pricing'
    | '/reports'
    | '/setup-admin'
    | '/upload'
    | '/analysis/$id'
    | '/settings/desktop'
    | '/api/internal/__cron-secret-once'
    | '/api/public/cron/purge-inactive'
    | '/api/public/desktop/pair'
    | '/api/public/desktop/submit-analysis'
    | '/api/public/desktop/whoami'
    | '/api/public/payments/plisio-webhook'
    | '/api/public/payments/webhook'
    | '/api/public/scripts/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ReportsRoute: typeof ReportsRoute
  SetupAdminRoute: typeof SetupAdminRoute
  UploadRoute: typeof UploadRoute
  AnalysisIdRoute: typeof AnalysisIdRoute
  SettingsDesktopRoute: typeof SettingsDesktopRoute
  ApiInternal_cronSecretOnceRoute: typeof ApiInternal_cronSecretOnceRoute
  ApiPublicCronPurgeInactiveRoute: typeof ApiPublicCronPurgeInactiveRoute
  ApiPublicDesktopPairRoute: typeof ApiPublicDesktopPairRoute
  ApiPublicDesktopSubmitAnalysisRoute: typeof ApiPublicDesktopSubmitAnalysisRoute
  ApiPublicDesktopWhoamiRoute: typeof ApiPublicDesktopWhoamiRoute
  ApiPublicPaymentsPlisioWebhookRoute: typeof ApiPublicPaymentsPlisioWebhookRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicScriptsFileRoute: typeof ApiPublicScriptsFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-admin': {
      id: '/setup-admin'
      path: '/setup-admin'
      fullPath: '/setup-admin'
      preLoaderRoute: typeof SetupAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/desktop': {
      id: '/settings/desktop'
      path: '/settings/desktop'
      fullPath: '/settings/desktop'
      preLoaderRoute: typeof SettingsDesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$id': {
      id: '/analysis/$id'
      path: '/analysis/$id'
      fullPath: '/analysis/$id'
      preLoaderRoute: typeof AnalysisIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/__cron-secret-once': {
      id: '/api/internal/__cron-secret-once'
      path: '/api/internal'
      fullPath: '/api/internal'
      preLoaderRoute: typeof ApiInternal_cronSecretOnceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scripts/$file': {
      id: '/api/public/scripts/$file'
      path: '/api/public/scripts/$file'
      fullPath: '/api/public/scripts/$file'
      preLoaderRoute: typeof ApiPublicScriptsFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/plisio-webhook': {
      id: '/api/public/payments/plisio-webhook'
      path: '/api/public/payments/plisio-webhook'
      fullPath: '/api/public/payments/plisio-webhook'
      preLoaderRoute: typeof ApiPublicPaymentsPlisioWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/desktop/whoami': {
      id: '/api/public/desktop/whoami'
      path: '/api/public/desktop/whoami'
      fullPath: '/api/public/desktop/whoami'
      preLoaderRoute: typeof ApiPublicDesktopWhoamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/desktop/submit-analysis': {
      id: '/api/public/desktop/submit-analysis'
      path: '/api/public/desktop/submit-analysis'
      fullPath: '/api/public/desktop/submit-analysis'
      preLoaderRoute: typeof ApiPublicDesktopSubmitAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/desktop/pair': {
      id: '/api/public/desktop/pair'
      path: '/api/public/desktop/pair'
      fullPath: '/api/public/desktop/pair'
      preLoaderRoute: typeof ApiPublicDesktopPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/purge-inactive': {
      id: '/api/public/cron/purge-inactive'
      path: '/api/public/cron/purge-inactive'
      fullPath: '/api/public/cron/purge-inactive'
      preLoaderRoute: typeof ApiPublicCronPurgeInactiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ReportsRoute: ReportsRoute,
  SetupAdminRoute: SetupAdminRoute,
  UploadRoute: UploadRoute,
  AnalysisIdRoute: AnalysisIdRoute,
  SettingsDesktopRoute: SettingsDesktopRoute,
  ApiInternal_cronSecretOnceRoute: ApiInternal_cronSecretOnceRoute,
  ApiPublicCronPurgeInactiveRoute: ApiPublicCronPurgeInactiveRoute,
  ApiPublicDesktopPairRoute: ApiPublicDesktopPairRoute,
  ApiPublicDesktopSubmitAnalysisRoute: ApiPublicDesktopSubmitAnalysisRoute,
  ApiPublicDesktopWhoamiRoute: ApiPublicDesktopWhoamiRoute,
  ApiPublicPaymentsPlisioWebhookRoute: ApiPublicPaymentsPlisioWebhookRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicScriptsFileRoute: ApiPublicScriptsFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
